version: 2

general:
  # Get Hypixel API key by creating one via dashboard.hypixel.net
  hypixelApiKey: '55adcfd6-abcd-477d-1234-12341234123a'

discord:
  # Create new discord bot from https://discordapp.com/developers and generate a secret key
  key: 'sgasihdgfiasgdiagsidiiagsd.sdfsaedf.aohdfoasfoieofi'
  # Discord ID of the USER who will have ADMIN permission
  adminIds: ['730667783180493755']

# Add custom plugins
plugins:
  - './src/plugins/example-plugin.ts'

metrics:
  enabled: false
  port: 9095
  # Prefix for prometheus metrics database
  prefix: 'guild_bridge_'
  # Send commands ingame to collect information such as online guild members, etc.
  # Sending repeated automated commands nonstop can be illegal
  useIngameCommand: false
  # Time in seconds to collect metrics from api/ingame commands
  interval: 60
