version: 2

general:
  # Get Hypixel API key by creating one via dashboard.hypixel.net
  hypixelApiKey: '55adcfd6-abcd-477d-1234-12341234123a'
  # Share basic anonymous metrics to display on the project main page as a way to show its popularity.
  # All metrics are anonymous and are limited to counting and never about anything specific
  shareMetrics: true

discord:
  # Create new discord bot from https://discordapp.com/developers and generate a secret key
  key: 'sgasihdgfiasgdiagsidiiagsd.sdfsaedf.aohdfoasfoieofi'
  # Discord ID of the USER who will have ADMIN permission
  adminIds: ['730667783180493755']

# Add custom plugins
plugins:
  - './src/plugins/example-plugin.ts'

prometheus:
  enabled: false
  port: 9095
  # Prefix for prometheus metrics database
  prefix: 'guild_bridge_'
