general:
  # Get Hypixel API key by creating one via dashboard.hypixel.net
  hypixelApiKey: '55adcfd6-abcd-477d-1234-12341234123a'

discord:
  instanceName: 'Discord'
  # Create new discord bot from https://discordapp.com/developers and generate a secret key
  key: 'sgasihdgfiasgdiagsidiiagsd.sdfsaedf.aohdfoasfoieofi'
  # Discord ID of the USER who will have ADMIN permission
  adminId: '730667783180493755'
  # Show Chat and public events in this channel id
  publicChannelIds: ['876718702164050860', 'another_channel']
  # Show Officer Chat and events in this channel id
  officerChannelIds: ['841257267059646432', 'another_channel']
  # Discord ID of the role who will have HELPER permission
  helperRoleIds: ['803266248652835111', 'another_role']
  # Discord ID of the role who will have OFFICER permission
  officerRoleIds: ['803266248652835111', 'another_role']

minecraft:
  # In-game USERNAME of the user who will have ADMIN permission
  adminUsername: 'Steve'
  # Minecraft account details
  instances:
    # name displayed on discord side
    - name: 'Good-Name'
      # This will only be used when initiating connection to minecraft server
      # Example: proxy: {protocol: "socks5", host: "example.com", port: 123}
      proxy: null

# Webhooks to log all internal events and metadata of the application
# for staff to preserve and inspect at later date
# This is an alternative to the log files
# since sometimes staff don't have access to system files
loggers:
  - 'https://discord.com/api/webhooks/...'

commands:
  # Enable chat commands such as !cata, etc.
  enabled: true

moderation:
  heatPunishment: true
  mutesPerDay: 10
  kicksPerDay: 5
  immune: []
  profanity:
    enabled: true
    whitelist: ['sadist', 'hell', 'damn', 'god', 'shit', 'balls', 'retard']
    blacklist: []

metrics:
  enabled: false
  port: 9095
  # Prefix for prometheus metrics database
  prefix: 'guild_bridge_'
  # Send commands ingame to collect information such as online guild members, etc.
  # Sending repeated automated commands nonstop can be illegal
  useIngameCommand: false
  # Time in seconds to collect metrics from api/ingame commands
  interval: 60

# Used to connect multiple applications together to share all their events
socket:
  enabled: false
  # Key used like a password.
  key: 'SECRET-KEY'
  # IP address or URL to connect to the server as the Client
  uri: 'ws://localhost:6090'
  # type could either be "client" or "server"
  # Server: The main application core that runs everything and control other nodes
  # Client: A node with single connection to main application
  type: 'client'
  # Port to listen as Server or to connect to as Client
  port: 6090

plugins:
  - './src/plugins/example-plugin.ts'
  - './src/plugins/limbo-plugin.ts'
  - './src/plugins/reaction-plugin.ts'
  - './src/plugins/dark-auction-plugin.ts'
  - './src/plugins/starfall-cult-plugin.ts'
  - './src/plugins/auto-restart-plugin.ts'
#  - './src/plugins/stuf-plugin.ts'
# Only enable after disabling limbo-plugin
#  - './src/plugins/warp-plugin.ts'
